# Generated by Django 4.2.9 on 2024-03-11 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_paragraph_parblog_delete_blog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BLGcreater', models.CharField(max_length=50, verbose_name='creater name')),
                ('BLGtitle', models.CharField(max_length=255)),
                ('BLGdate', models.DateTimeField(verbose_name='Date')),
                ('BLGimage', models.ImageField(blank=True, null=True, upload_to='images/%y/%m/%d', verbose_name='blog image')),
                ('BLGcontent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PARtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='title of paragraph')),
                ('PARimage', models.ImageField(blank=True, null=True, upload_to='images/%y/%m/%d', verbose_name='blog image')),
                ('PARcontent', models.TextField()),
                ('PARblog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='core.blog')),
            ],
        ),
    ]
