# Generated by Django 4.2.9 on 2024-03-13 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='BLGcreater',
            new_name='BLGcreator',
        ),
    ]
