# Generated by Django 4.2.9 on 2024-03-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='BLGdate',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
