# Generated by Django 4.2.9 on 2024-03-15 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_blog_blgdate_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CMTdate', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Date')),
                ('CMTusername', models.CharField(max_length=255)),
                ('CMTemail', models.EmailField(max_length=254)),
                ('CMTcomment', models.TextField()),
                ('CMTblog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.blog')),
            ],
        ),
    ]
