# Generated by Django 4.2.9 on 2024-03-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_blog_blgheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CMTdate', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Date')),
                ('CMTemail', models.EmailField(max_length=254)),
                ('PARimage', models.ImageField(upload_to='users_photo/%y/%m/%d', verbose_name='users')),
            ],
        ),
    ]
