# Generated by Django 4.2.9 on 2024-03-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_cmtdate_userdata_uddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='UDimage',
            field=models.ImageField(default='\\static\\img\\defaultOIP.jpg', upload_to='users_photo/%y/%m/%d', verbose_name='users'),
        ),
    ]
