# Generated by Django 4.2.9 on 2024-03-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_userdata_udimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
        migrations.AddField(
            model_name='comment',
            name='CMTimage',
            field=models.ImageField(default='\\static\\img\\default\\OIP.jpg', upload_to='users_photo/%y/%m/%d', verbose_name='users'),
        ),
    ]
