# Generated by Django 4.2.9 on 2024-03-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_comment_cmtimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='CMTimage',
            field=models.ImageField(upload_to='users_photo/%y/%m/%d', verbose_name='users'),
        ),
    ]
