# Generated by Django 4.2.9 on 2024-03-19 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_comment_cmtimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='CMTimage',
        ),
    ]
