# Generated by Django 4.2.9 on 2024-03-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_comment_cmtimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='BLGimage',
            field=models.ImageField(default='images/tourism', upload_to='images/%y/%m/%d', verbose_name='blog image'),
        ),
    ]
