# Generated by Django 4.2.9 on 2024-03-21 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_blog_blgimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WRTRname', models.CharField(max_length=50, verbose_name='name')),
                ('WRTRimage', models.ImageField(upload_to='writer/%y/%m/%d', verbose_name='photo')),
                ('WRTRbio', models.TextField(verbose_name='bio')),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='BLGcreator',
        ),
        migrations.AddField(
            model_name='blog',
            name='BLGwriter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.writer', verbose_name='writer'),
        ),
    ]
