# Generated by Django 4.2.9 on 2024-03-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_blog_blgwriter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='WRTRimage',
            field=models.ImageField(blank=True, null=True, upload_to='writer/%y/%m/%d', verbose_name='photo'),
        ),
    ]
